# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", bridge: "LAN"
  config.vm.provision "file", source: "F:/_work/_pers/key/pub.txt", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.define :centos1 do |centos1|
    centos1.vm.provision :shell, :path => "set-ip.sh", :args => "10.0.0.50"
    centos1.vm.provision :reload
  end

  config.vm.define :centos2 do |centos2|
    centos2.vm.provision :shell, :path => "set-ip.sh", :args => "10.0.0.51"
    centos2.vm.provision :reload
  end

  config.vm.define :centos3 do |centos3|
    centos3.vm.provision :shell, :path => "set-ip.sh", :args => "10.0.0.52"
    centos3.vm.provision :reload
  end
end