# -*- mode: ruby -*-

nodes = {
  "centos1" => "10.0.0.50",
  "centos2" => "10.0.0.51",
  "centos3" => "10.0.0.52",
  "centos4" => "10.0.0.53"
}

Vagrant.configure("2") do |config|
  config.vm.box = "pavelpanfilov/centos-k8s"
  config.vm.box_version = "0.0.1"
  config.vm.network "public_network", bridge: "LAN"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |vb|
      vb.maxmemory = "2048"
      vb.cpus = "2"
  end
  config.vm.provision "file", source: "F:/_work/_pers/key/pub.txt", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  config.vm.provision :shell, path: "bootstrap.sh"

  nodes.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.provision :shell, :path => "set-ip.sh", :args => ip
      machine.vm.provision :reload
      machine.vm.provision :hostmanager
    end
  end
end